apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-spring-data-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: rest-spring-data
  template:
    metadata:
      labels:
        component: rest-spring-data
    spec:
      containers:
        - name: rest-spring-data
          image: wahuu/booking-rest-spring-data
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_USERNAME
              value: postgres
            - name: DB_PORT
              value: '5432'
            - name: DB_NAME
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: '6379'